apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "demo-gradle.fullname" . }}
{{- end }}
  labels:
{{ include "demo-gradle.labels.standard" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
    # heritage: {{.Release.Service | quote }}
    # release: {{.Release.Name | quote }}
    # chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.hostName }}.{{ .Values.ingress.baseDomain }}"
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- end }}
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: {{ .Values.service.ports.protocol }}
  selector:
    app: {{ template "demo-gradle.name" . }}
    release: {{ .Release.Name | quote }}